<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Database\Factories\TaskFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;


    protected $guarded =[];

    protected $touches = ['project'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($task){
            $task->project->recordActivity('created_task');
        });
    }
    public function complete()
    {
        $this->update(['completed' => Carbon::now()]);

        $this->project->recordActivity('completed_task');
    }
    public function uncomplete()
    {
        $this->update(['completed' => NULL]);

        $this->project->recordActivity('uncompleted_task');
    }


    public function project()
    {
        return $this->belongsTo(Project::class );
    }

    public function path()
    {
        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }
}
